# =============================================================================
# CTestTestfile.cmake - Test Labels for Mandatory Gating
# =============================================================================
# Generated by Sirius build system
# Governance: docs/specification.md, Test Coverage Requirements
#
# Labels:
#   Mandatory   - Build fails if these tests fail
#   Correctness - Mathematical invariant tests
#   Stability   - Numerical stability tests
#   Performance - FPS/resource metrics (warning only)
# =============================================================================

# Apply labels by test name patterns
set_tests_properties(
    DualNumberTests.AdditiveIdentity
    DualNumberTests.MultiplicativeIdentity
    DualNumberTests.AdditiveInverse
    DualNumberTests.AdditionCommutativity
    DualNumberTests.MultiplicationCommutativity
    DualNumberTests.AdditionAssociativity
    DualNumberTests.Distributivity
    DualNumberTests.Nilpotency
    DualNumberTests.ProductFormula
    DualNumberTests.DivisionFormula
    DualNumberTests.SinDerivative
    DualNumberTests.SinDerivativeMultipleAngles
    DualNumberTests.CosDerivative
    DualNumberTests.SqrtDerivative
    DualNumberTests.SqrtDerivativeMultiplePoints
    DualNumberTests.ChainRuleSinSquare
    PROPERTIES LABELS "Mandatory;Correctness"
)

set_tests_properties(
    TensorTests.VectorZeroInitialization
    TensorTests.VectorElementAccess
    TensorTests.VectorAddition
    TensorTests.VectorScalarMultiplication
    TensorTests.VectorLength
    TensorTests.VectorUnaryMinus
    TensorTests.MatrixZeroInitialization
    TensorTests.MinkowskiSymmetry
    TensorTests.MinkowskiDiagonal
    TensorTests.MinkowskiSignature
    TensorTests.InnerProductSpatial
    TensorTests.NullVectorInnerProduct
    TensorTests.Tensor3ZeroInitialization
    TensorTests.FlatSpaceChristoffelZero
    TensorTests.ChristoffelSymmetry
    PROPERTIES LABELS "Mandatory;Correctness"
)

set_tests_properties(
    SchwarzschildTests.MetricIsDiagonal
    SchwarzschildTests.MetricIsSymmetric
    SchwarzschildTests.MetricHasLorentzianSignature
    SchwarzschildTests.AsymptoticFlatness
    SchwarzschildTests.EventHorizonGtt
    PROPERTIES LABELS "Mandatory;Correctness"
)

set_tests_properties(
    ChristoffelTests.ChristoffelSymmetry
    ChristoffelTests.MinkowskiChristoffelsZero
    ChristoffelTests.SchwarzschildChristoffelNonZero
    PROPERTIES LABELS "Mandatory;Correctness"
)

set_tests_properties(
    GeodesicEquationTests.FlatSpaceAccelerationZero
    GeodesicEquationTests.NullVelocityPreserved
    PROPERTIES LABELS "Mandatory;Correctness"
)

set_tests_properties(
    KerrMetricTests.MetricIsSymmetric
    KerrMetricTests.ReducesToMinkowskiFarField
    KerrMetricTests.ReducesToSchwarzchildZeroSpin
    KerrMetricTests.FrameDraggingTermExists
    KerrMetricTests.MetricHasLorentzianSignature
    PROPERTIES LABELS "Mandatory;Correctness"
)

set_tests_properties(
    ReissnerNordstromTests.MetricIsDiagonal
    ReissnerNordstromTests.MetricIsSymmetric
    ReissnerNordstromTests.MetricHasLorentzianSignature
    ReissnerNordstromTests.ReducesToSchwarzschildZeroCharge
    ReissnerNordstromTests.AsymptoticFlatness
    ReissnerNordstromTests.OuterHorizonFormula
    ReissnerNordstromTests.DeterminantIsNegative
    PROPERTIES LABELS "Mandatory;Correctness"
)

set_tests_properties(
    NumericalMetricTests.MinkowskiADMReturnsMinkowski
    NumericalMetricTests.MetricIsSymmetric
    NumericalMetricTests.MetricHasNegativeGtt
    NumericalMetricTests.InverseMetricIdentity
    NumericalMetricTests.SchwarzschildAsymptoticFlatness
    NumericalMetricTests.NoNaNInMetric
    PROPERTIES LABELS "Mandatory;Correctness"
)

# Stability tests - mandatory for production
set_tests_properties(
    NumericalStabilityTests.DualZeroHandling
    NumericalStabilityTests.DualDivisionBySmall
    NumericalStabilityTests.DualSqrtNearZero
    NumericalStabilityTests.SchwarzschildNearHorizon
    PROPERTIES LABELS "Mandatory;Stability"
)

# Benchmark tests - performance validation (soft gate)
set_tests_properties(
    GeodesicBenchmarks.CircularOrbitPeriod
    GeodesicBenchmarks.ISCORadius
    GeodesicBenchmarks.PhotonSphereRadius
    GeodesicBenchmarks.WeakFieldLightDeflection
    GeodesicBenchmarks.SolarDeflectionOrder
    GeodesicBenchmarks.GeodesicConservedQuantities
    GeodesicBenchmarks.RadialFallProperTime
    GeodesicBenchmarks.PerihelionPrecession
    GeodesicBenchmarks.VerificationDataPoints
    PROPERTIES LABELS "Correctness"
)

# FPS benchmark tests - performance validation (soft gate)
set_tests_properties(
    FPSBenchmarks.MinkowskiFPS
    FPSBenchmarks.SchwarzschildFPS
    FPSBenchmarks.SchwarzschildNearHorizonFPS
    FPSBenchmarks.KerrFPS
    FPSBenchmarks.KerrSpinComparison
    FPSBenchmarks.MetricComparison
    FPSBenchmarks.StepCountScaling
    PROPERTIES LABELS "Performance"
)

# Metric loader chain integration tests
set_tests_properties(
    MetricLoaderChainTests.AllMetricsHaveName
    MetricLoaderChainTests.AllMetricsEvaluateAtStandardPosition
    MetricLoaderChainTests.AllMetricsHaveLorentzianSignature
    MetricLoaderChainTests.AllMetricsAreSymmetric
    MetricLoaderChainTests.KerrReducesToSchwarzschild
    MetricLoaderChainTests.RNReducesToSchwarzschild
    MetricLoaderChainTests.FarFieldAsymptoticFlatness
    MetricLoaderChainTests.MinkowskiIsExactlyFlat
    MetricLoaderChainTests.SequentialEvaluationsStable
    PROPERTIES LABELS "Mandatory;Correctness"
)

# FPS threshold tests (TSPF001A)
set_tests_properties(
    FPSThresholdTests.FrameBudgetCalculations
    FPSThresholdTests.ResolutionCalculations
    FPSThresholdTests.TargetsExceedBounds
    FPSThresholdTests.MinkowskiEvaluationTime
    FPSThresholdTests.MetricComplexityOrdering
    FPSThresholdTests.EvaluationConsistency
    FPSThresholdTests.NoNaNInCriticalPath
    PROPERTIES LABELS "Performance"
)

# Memory usage tests (TSPF002A)
set_tests_properties(
    MemoryUsageTests.FundamentalTypeSizes
    MemoryUsageTests.DualNumberSize
    MemoryUsageTests.Vec4Size
    MemoryUsageTests.Metric4DSize
    MemoryUsageTests.PerRayMemory
    MemoryUsageTests.NumericalMetricSmallGrid
    MemoryUsageTests.TotalVRAMAnalytic1080p
    MemoryUsageTests.TotalVRAMNumerical1080p
    MemoryUsageTests.VectorAllocationSafe
    MemoryUsageTests.MetricEvaluationNoLeak
    PROPERTIES LABELS "Performance"
)

# =============================================================================
# RESOLVED: Tests now passing with RK45 integrator (Dec 2024)
# =============================================================================
# These tests previously failed with the Störmer-Verlet integrator but now
# pass after upgrading to adaptive RK45 (Dormand-Prince) integration.
# Conservation law tests verify bounded drift over 1000 integration steps.
# =============================================================================
set_tests_properties(
    ConservationLawTests.NullConditionPreservedSchwarzschild
    ConservationLawTests.NullConditionPreservedKerr
    ConservationLawTests.KillingEnergyConservedKerr
    ConservationLawTests.AllConservedQuantitiesSchwarzschild
    ConservationLawTests.KillingEnergyConservedSchwarzschild
    ConservationLawTests.KillingAngularMomentumConservedSchwarzschild
    ConservationLawTests.KillingAngularMomentumConservedKerr
    PROPERTIES LABELS "Mandatory;Stability"
)

# Geodesic path tests that now pass with RK45
# Note: PhotonSphereRadius and RadialInfallApproachesHorizon are DISABLED
# as they test inherently unstable behaviors
set_tests_properties(
    GeodesicPathTests.PhotonSphereInstability
    GeodesicPathTests.WeakFieldLightDeflection
    GeodesicPathTests.KerrFrameDragging
    GeodesicPathTests.PhiWrapContinuity
    GeodesicPathTests.MetricSignatureCorrect
    GeodesicPathTests.KerrMetricSignature
    PROPERTIES LABELS "Correctness"
)

# Determinism tests - mandatory for production reproducibility
set_tests_properties(
    DeterminismTests.DualArithmeticDeterminism
    DeterminismTests.SchwarzschildMetricDeterminism
    DeterminismTests.KerrMetricDeterminism
    DeterminismTests.ChristoffelDeterminism
    DeterminismTests.GeodesicIntegrationDeterminism
    DeterminismTests.InnerProductDeterminism
    DeterminismTests.NullNormalizationDeterminism
    PROPERTIES LABELS "Mandatory;Stability"
)

# Metric derivative validation tests (TSPH012A)
set_tests_properties(
    MetricDerivativeTests.KerrSchildDerivativeSymmetry
    MetricDerivativeTests.KerrSchildFiniteDifferenceAgreement
    MetricDerivativeTests.KerrSchildNonZeroDerivatives
    MetricDerivativeTests.EllisDrainholeDerivativeSymmetry
    MetricDerivativeTests.EllisDrainholeRadialDerivative
    MetricDerivativeTests.EllisDrainholeAngularDerivative
    MetricDerivativeTests.EllisDrainholeFiniteDifferenceAgreement
    MetricDerivativeTests.AlcubierreDerivativeSymmetry
    MetricDerivativeTests.AlcubierreTimeDerivative
    MetricDerivativeTests.AlcubirrreFiniteDifferenceAgreement
    MetricDerivativeTests.AlcubierreOutsideBubble
    MetricDerivativeTests.ChristoffelSymmetryFromDerivatives
    PROPERTIES LABELS "Mandatory;Correctness"
)

# DNGR validation tests - FIDO frame consistency (TSCM005A)
set_tests_properties(
    FIDOFrameTests.RhoComputationCorrect
    FIDOFrameTests.DeltaComputationCorrect
    FIDOFrameTests.FrameDraggingZeroForSchwarzschild
    FIDOFrameTests.FrameDraggingIncreasesWithSpin
    FIDOFrameTests.LapseFunctionLessThanOne
    FIDOFrameTests.LapseFunctionApproachesOneAtInfinity
    FIDOFrameTests.FIDOBasisOrthonormalAtEquator
    FIDOFrameTests.CircularGeodesicSpeedSubluminal
    FIDOFrameTests.CircularGeodesicSpeedIncreasesNearHorizon
    FIDOFrameTests.SchwarzschildCircularSpeed
    FIDOFrameTests.KerrReducesToSchwarzschildAtZeroSpin
    PROPERTIES LABELS "Correctness"
)

# DNGR validation tests - G-factor (TSCM006A)
set_tests_properties(
    GFactorTests.StaticCameraGravitationalRedshift
    GFactorTests.SRFactorOneWhenStationary
    GFactorTests.ApproachingRayBlueshift
    GFactorTests.RecedingRayRedshift
    GFactorTests.TransverseRayDoppler
    GFactorTests.FrameDraggingEffect
    GFactorTests.NoFrameDraggingInSchwarzschild
    GFactorTests.SchwarzschildISCOGravitationalRedshift
    GFactorTests.AsymptoticGFactorApproachesOne
    GFactorTests.GFactorAlwaysPositive
    GFactorTests.GFactorIsFinite
    GFactorTests.HighSpeedApproachingBlueshift
    GFactorTests.HighSpeedRecedingRedshift
    PROPERTIES LABELS "Correctness"
)

# DNGR validation tests - Geodesic deviation (TSCM007A)
set_tests_properties(
    GeodesicDeviationTests.MinkowskiRiemannZero
    GeodesicDeviationTests.DeviationConstantInFlatSpace
    GeodesicDeviationTests.SchwarzschildRiemannNonzero
    GeodesicDeviationTests.RiemannDecreasesWithDistance
    GeodesicDeviationTests.EllipseSemiAxesPositive
    GeodesicDeviationTests.CircularBundleInitialization
    GeodesicDeviationTests.BundleInitializationCorrect
    GeodesicDeviationTests.PropagationRemainsFinite
    PROPERTIES LABELS "Correctness"
)

# =============================================================================
# MANDATORY: Killing Vector Conservation Tests (TSDG006A)
# =============================================================================
# These tests verify that Killing vector conserved quantities (energy, angular
# momentum) remain bounded during geodesic integration. Required for all
# stationary and axisymmetric spacetimes.
set_tests_properties(
    MandatoryKillingTests.SchwarzschildEnergyConservation
    MandatoryKillingTests.SchwarzschildAngularMomentumConservation
    MandatoryKillingTests.KerrEnergyConservation
    MandatoryKillingTests.KerrAngularMomentumConservation
    MandatoryKillingTests.ReissnerNordstromEnergyConservation
    PROPERTIES LABELS "Mandatory;Stability"
)

# =============================================================================
# GPU Conservation Validation Tests (TSDG005A)
# =============================================================================
set_tests_properties(
    GPUConservationTests.DebugBufferAnalysis
    GPUConservationTests.SpecificationCompliance
    PROPERTIES LABELS "Mandatory;Stability"
)

# =============================================================================
# GPU/CPU Parity Tests (TSIN006A)
# =============================================================================
set_tests_properties(
    CPUGPUParityTests.BaselineCPUIntegration
    CPUGPUParityTests.ReferenceRayGridGeneration
    PROPERTIES LABELS "Mandatory;Correctness"
)

# =============================================================================
# Spectral Validation Tests (TSSP002A)
# =============================================================================
set_tests_properties(
    SpectralValidationTests.PlanckFunctionBasic
    SpectralValidationTests.PlanckFunctionMonotonicity
    SpectralValidationTests.WienDisplacementLaw
    SpectralValidationTests.SolarPeakWavelength
    SpectralValidationTests.CandelaColor
    SpectralValidationTests.WienKnownValues
    SpectralValidationTests.RedshiftIntensityScaling
    SpectralValidationTests.RedshiftWavelengthTransform
    SpectralValidationTests.ColorTemperatureOrdering
    SpectralValidationTests.LimbDarkeningCoefficient
    SpectralValidationTests.BlackbodyColorProgression
    SpectralValidationTests.StefanBoltzmannLaw
    SpectralValidationTests.SolarLuminosity
    PROPERTIES LABELS "Correctness"
)

# =============================================================================
# Analytic Validation Tests (TSDG008A)
# =============================================================================
set_tests_properties(
    AnalyticValidationTests.SchwarzschildHorizonRadius
    AnalyticValidationTests.SchwarzschildPhotonSphere
    AnalyticValidationTests.SchwarzschildISCO
    AnalyticValidationTests.SchwarzschildOrbitalVelocity
    AnalyticValidationTests.KerrHorizonRadius
    AnalyticValidationTests.KerrISCOPrograde
    AnalyticValidationTests.KerrISCODecreaseWithSpin
    AnalyticValidationTests.KerrErgosphereAtEquator
    AnalyticValidationTests.KerrErgosphereAtPole
    AnalyticValidationTests.WeakFieldDeflectionFormula
    AnalyticValidationTests.SolarDeflectionOrderOfMagnitude
    AnalyticValidationTests.KerrReducesToSchwarzschildAtZeroSpin
    AnalyticValidationTests.AsymptoticFlatness
    AnalyticValidationTests.SchwarzschildKretschmannScalar
    AnalyticValidationTests.KretschmannMonotonicDecrease
    AnalyticValidationTests.HorizonMetricDegeneracy
    AnalyticValidationTests.SchwarzschildISCOEnergy
    PROPERTIES LABELS "Mandatory;Correctness"
)

# =============================================================================
# Polarisation Tests (TSPL001A) - Stokes/Mueller formalism
# =============================================================================
set_tests_properties(
    StokesVectorTests.UnpolarisedConstruction
    StokesVectorTests.HorizontalPolarisation
    StokesVectorTests.VerticalPolarisation
    StokesVectorTests.CircularPolarisation
    StokesVectorTests.PhysicalConstraint
    StokesVectorTests.PolarisationDegree
    StokesVectorTests.LinearPolarisationDegree
    StokesVectorTests.CircularPolarisationDegree
    StokesVectorTests.EVPAComputation
    StokesVectorTests.IsPhysicalRejectsUnphysical
    StokesVectorTests.NormalisationProjection
    StokesVectorTests.ZeroIntensityHandling
    StokesVectorTests.ArithmeticOperators
    MuellerMatrixTests.IdentityPreservesStokes
    MuellerMatrixTests.HorizontalPolariserOnUnpolarised
    MuellerMatrixTests.VerticalPolariserOnUnpolarised
    MuellerMatrixTests.CrossedPolariersExtinguish
    MuellerMatrixTests.QuarterWavePlateConvertsToCircular
    MuellerMatrixTests.CompositionAssociativity
    MuellerMatrixTests.DepolariserReducesPolarisation
    MuellerMatrixTests.HalfWavePlateFlipsHandedness
    PolarisedEmissionTests.SynchrotronPolarisationDegree
    PolarisedEmissionTests.SynchrotronEmissionIsPhysical
    PolarisedEmissionTests.ThomsonScatteringAt90Degrees
    PolarisedEmissionTests.ThomsonScatteringForward
    ParallelTransportTests.ZeroSpinNoRotation
    ParallelTransportTests.RotationIncreasesWithSpin
    ParallelTransportTests.ApplyPreservesIntensity
    PROPERTIES LABELS "Mandatory;Correctness"
)

# =============================================================================
# Alcubierre Warp Drive Metric Tests (TSMT102A)
# =============================================================================
set_tests_properties(
    AlcubierreMetricTests.MetricSymmetry
    AlcubierreMetricTests.LorentzianSignature
    AlcubierreMetricTests.ReducesToMinkowskiOutside
    AlcubierreMetricTests.ShiftVectorAtCentre
    AlcubierreMetricTests.GttAtCentre
    AlcubierreMetricTests.SpatialComponentsFlat
    AlcubierreMetricTests.ShapeFunctionAtCentre
    AlcubierreMetricTests.ShapeFunctionFarField
    AlcubierreMetricTests.ShapeFunctionMonotoneDecrease
    AlcubierreMetricTests.ShapeFunctionDerivativeFinite
    AlcubierreMetricTests.SubluminalConstruction
    AlcubierreMetricTests.SuperluminalConstruction
    AlcubierreMetricTests.SetParameterClamping
    AlcubierreMetricTests.NoNaNAtBubbleWall
    AlcubierreMetricTests.NoNaNAtOrigin
    AlcubierreMetricTests.BubblePositionUpdate
    PROPERTIES LABELS "Mandatory;Correctness"
)

# =============================================================================
# Corona Model Tests (TSCR001A)
# =============================================================================
set_tests_properties(
    CoronaConfigTests.ValidateClampsTemperature
    CoronaConfigTests.ValidateClampsOpticalDepth
    CoronaConfigTests.ValidateEnsuresOuterGreaterThanInner
    CoronaConfigTests.ComptonizationParameter
    CoronaConfigTests.ComptonizationHighOpticalDepth
    CoronaConfigTests.SpectralIndexFinite
    CoronaGeometryTests.DisabledReturnsNoContainment
    CoronaGeometryTests.OutsideRadialBoundsRejected
    CoronaGeometryTests.SlabGeometryEquatorialInside
    CoronaGeometryTests.SlabGeometryPolarOutside
    CoronaGeometryTests.LamppostNearSourceInside
    CoronaGeometryTests.SphereContainment
    CoronaGeometryTests.ExtendedScalesWithRadius
    CoronaEmissivityTests.ZeroOutsideBounds
    CoronaEmissivityTests.DisabledReturnsZero
    CoronaEmissivityTests.DecreasesWithRadius
    CoronaEmissivityTests.GaussianVerticalFalloff
    CoronaEmissivityTests.OpticalDepthDisabledIsZero
    CoronaEmissivityTests.OpticalDepthPositiveInsideCorona
    CoronaEmissivityTests.ScatteredIntensityZeroForZeroTau
    CoronaEmissivityTests.ScatteredIntensityIncreasesWithTau
    PROPERTIES LABELS "Correctness"
)

# =============================================================================
# Coordinate Utility Tests (TSCT001A)
# =============================================================================
set_tests_properties(
    CoordUtilityTests.RoundTripCartesianSpherical
    CoordUtilityTests.RoundTripSphericalCartesian
    CoordUtilityTests.OriginHandling
    CoordUtilityTests.NorthPole
    CoordUtilityTests.SouthPole
    CoordUtilityTests.KnownValueXAxis
    CoordUtilityTests.KnownValueZAxis
    CoordUtilityTests.FourVectorTimePassthrough
    CoordUtilityTests.VelocityRoundTrip
    CoordUtilityTests.VelocityTimeComponentUnchanged
    CoordUtilityTests.KerrRadiusZeroSpin
    CoordUtilityTests.KerrRadiusPositive
    CoordUtilityTests.EquirectangularBounds
    CoordUtilityTests.EquirectangularPoles
    CoordUtilityTests.InAccretionDisk
    CoordUtilityTests.CylindricalRadius
    CoordUtilityTests.AzimuthalAngle
    CoordUtilityTests.SIMDBatchRoundTrip
    CoordUtilityTests.SIMDScalarParity
    PROPERTIES LABELS "Mandatory;Correctness"
)

# =============================================================================
# Transport Type Tests (TSTP001A)
# =============================================================================
set_tests_properties(
    Vec4dTests.DefaultConstructionAllZeros
    Vec4dTests.ParameterisedConstruction
    Vec4dTests.IndexedAccess
    Vec4dTests.IndexedMutation
    Vec4dTests.Addition
    Vec4dTests.Subtraction
    Vec4dTests.ScalarMultiplication
    Vec4dTests.ScalarMultiplicationCommutative
    Vec4dTests.ScalarDivision
    Vec4dTests.CompoundAssignment
    Vec4dTests.Negation
    Vec4dTests.Norm2
    Vec4dTests.IsZero
    GeodesicStateDTests.DefaultConstruction
    GeodesicStateDTests.ConstructionFromPosAndMom
    GeodesicStateDTests.ConservedQuantitiesSchwarzschildLike
    HamiltonianStateDTests.DefaultConstruction
    HamiltonianStateDTests.RoundTripViaGeodesicState
    HamiltonianStateDTests.ConstructFromGeodesicState
    Mat4dTests.DefaultIsZero
    Mat4dTests.IdentityDiagonal
    Mat4dTests.Trace
    Mat4dTests.IdentityDeterminant
    Mat4dTests.ZeroDeterminant
    Mat4dTests.KnownDeterminant
    Mat4dTests.MatrixVectorMultiplication
    Mat4dTests.ScalarMultiplication
    Mat4dTests.Addition
    ConversionTests.ToVec4dFromFloats
    ConversionTests.ToFloat4RoundTrip
    PROPERTIES LABELS "Mandatory;Correctness"
)

# =============================================================================
# Post-Processing Tests (TSPP001A)
# =============================================================================
set_tests_properties(
    TonemapTests.ACESAtZero
    TonemapTests.ACESMonotone
    TonemapTests.ACESBounded
    TonemapTests.ReinhardAnalytic
    TonemapTests.FilmicAtZero
    TonemapTests.FilmicMonotone
    TonemapTests.FilmicBounded
    TonemapTests.AgXAtZero
    TonemapTests.AgXMonotone
    TonemapTests.AgXBounded
    TonemapTests.ApplyExposureScaling
    TonemapTests.ApplyACESDispatch
    TonemapTests.ApplyReinhardDispatch
    BloomFilterTests.DisabledBloomLeavesBufferUnchanged
    BloomFilterTests.ZeroIntensityBloomLeavesUnchanged
    BloomFilterTests.BrightPixelsCauseBloom
    ColourGradingTests.IdentityParametersPreserveValues
    ColourGradingTests.ZeroSaturationProducesGrey
    ColourGradingTests.OutputClamped
    PROPERTIES LABELS "Correctness"
)

# =============================================================================
# Jet Emission Tests (TSJT001A)
# =============================================================================
set_tests_properties(
    JetDopplerTests.HeadOnApproachBoosted
    JetDopplerTests.RecedingDeBoosted
    JetDopplerTests.TransverseDirection
    JetDopplerTests.AnalyticFormula
    JetGeometryTests.InsideJetOnAxis
    JetGeometryTests.OutsideJetBelowLaunch
    JetGeometryTests.OutsideJetFarOffAxis
    JetGeometryTests.SouthernJet
    JetGeometryTests.JetRadiusMonotone
    JetGeometryTests.JetRadiusZeroBelowLaunch
    JetEmissionTests.MagneticFieldAtLaunch
    JetEmissionTests.MagneticFieldDecays
    JetEmissionTests.ElectronDensityAtLaunch
    JetEmissionTests.ElectronDensityDecays
    JetEmissionTests.SynchrotronEmissivityPositive
    JetEmissionTests.BeamingApproachingBrighterThanReceding
    JetEmissionTests.PolarisationDegreeFormula
    JetEmissionTests.VelocityDirection
    JetRayMarchTests.EmissionOutsideJetIsZero
    PROPERTIES LABELS "Correctness"
)

# =============================================================================
# Starfield Tests (TSSF001A)
# =============================================================================
set_tests_properties(
    StarfieldConfigTests.ValidateClampsStarCount
    StarfieldConfigTests.ValidateClampsMinDistance
    StarfieldConfigTests.ValidateEnsuresMaxGreaterThanMin
    StarfieldConfigTests.ValidateClampsMagnitudeLimit
    StarfieldConfigTests.ValidateClampsAperture
    StarEntryTests.ComputeColorProducesValidRGB
    StarEntryTests.HotStarIsBluer
    StarEntryTests.ZeroTemperatureDefaultsToSolar
    StarEntryTests.IntensityFromMagnitude
    StarEntryTests.IntensityMagnitudeRelation
    StarfieldGeneratorTests.GeneratesNonEmptyCatalog
    StarfieldGeneratorTests.CatalogSizeBounded
    StarfieldGeneratorTests.DirectionVectorsNormalised
    StarfieldGeneratorTests.AllTemperaturesPositive
    StarfieldGeneratorTests.AllDistancesPositive
    StarfieldGeneratorTests.DeterministicWithSameSeed
    StarfieldGeneratorTests.DifferentSeedsDifferentCatalogs
    StarfieldGeneratorTests.NoNaNInCatalog
    PROPERTIES LABELS "Correctness"
)

# =============================================================================
# Camera Lens Model Tests (TSCM001A)
# =============================================================================
set_tests_properties(
    PinholeCameraTest.CentreRayPointsInward
    PinholeCameraTest.RayDirectionIsNormalised
    PinholeCameraTest.OriginMatchesConfig
    PinholeCameraTest.RightPixelIncreasesAzimuth
    PinholeCameraTest.UpPixelDecreasesTheta
    PinholeCameraTest.WeightIsOne
    PinholeCameraTest.TimeComponentIsZero
    ThinLensCameraTest.CentreRayWithDefaultSampling
    ThinLensCameraTest.DifferentSamplesGiveDifferentRays
    FisheyeCameraTest.CentreRayPointsInward
    FisheyeCameraTest.EdgeRayPerpendicularAt180Fov
    FisheyeCameraTest.OutOfBoundsRayHasZeroWeight
    CameraFactoryTest.CreatePinhole
    CameraFactoryTest.CreateThinLens
    CameraFactoryTest.CreateFisheye
    CameraFactoryTest.DefaultFallsToPinhole
    CameraFactoryTest.ConfigPassthrough
    ICameraTest.GetPositionReturnsConfigCoordinates
    ICameraTest.SetConfigUpdatesRayGeneration
    PROPERTIES LABELS "Mandatory;Correctness"
)

# =============================================================================
# Beam Sampling and Scene Intersection Tests (TSSI002A)
# =============================================================================
set_tests_properties(
    BeamSamplerTest.GaussianWeightDecay
    BeamSamplerTest.EllipseOrientation
    BeamSamplerTest.SolidAngleComputation
    SceneIntersectorTest.DiskJacobianTransform
    SceneIntersectorTest.DiskIntersectionDetection
    SceneIntersectorTest.CelestialSphereDetection
    SceneIntersectorTest.HorizonDetection
    SceneIntersectorTest.DiskEmissionHasRedshift
    PROPERTIES LABELS "Correctness"
)

# =============================================================================
# Boyer-Lindquist Coordinate Transform Tests (TSPH015A)
# =============================================================================
set_tests_properties(
    BLCartesianTests.RoundTripBLCartesian_Equator
    BLCartesianTests.RoundTripBLCartesian_NearPole
    BLCartesianTests.RoundTripBLCartesian_FarField
    BLCartesianTests.RoundTripBLCartesian_NearHorizon
    KerrSchildRoundTripTests.RoundTripKerrSchild_LowSpin
    KerrSchildRoundTripTests.RoundTripKerrSchild_ModerateSpin
    KerrSchildRoundTripTests.RoundTripKerrSchild_HighSpin
    KerrSchildRoundTripTests.RoundTripKerrSchild_NearPole
    JacobianTests.JacobianDeterminant_Equator
    JacobianTests.JacobianDeterminant_MidLatitude
    VectorTransformTests.VectorTransformRoundTrip
    BoundaryTests.OriginHandling
    BoundaryTests.PhiWrapping
    BoundaryTests.NorthPoleCoordinates
    BoundaryTests.SouthPoleCoordinates
    KerrSpecificTests.KerrOblateSpheroidal
    KerrSpecificTests.KerrSolveR_Accuracy
    PROPERTIES LABELS "Mandatory;Correctness"
)

# =============================================================================
# GPU/CPU Blackbody Parity Tests (TSSP003A)
# =============================================================================
set_tests_properties(
    ReferenceTemperatures/BlackbodyParityTest.GPUMatchesCPU/0
    ReferenceTemperatures/BlackbodyParityTest.GPUMatchesCPU/1
    ReferenceTemperatures/BlackbodyParityTest.GPUMatchesCPU/2
    ReferenceTemperatures/BlackbodyParityTest.GPUMatchesCPU/3
    ReferenceTemperatures/BlackbodyParityTest.GPUMatchesCPU/4
    BlackbodyParityTest.ColourTemperatureOrdering
    PROPERTIES LABELS "Correctness"
)

# =============================================================================
# Spectral Emission Pipeline Tests (TSIN007A)
# =============================================================================
set_tests_properties(
    SpectralEmissionTest.NT_QFactorZeroAtISCO_Schwarzschild
    SpectralEmissionTest.NT_QFactorZeroAtISCO_Kerr
    SpectralEmissionTest.NT_QFactorPositiveOutsideISCO
    SpectralEmissionTest.NT_QFactorBounded
    SpectralEmissionTest.TemperatureRange
    SpectralEmissionTest.BlackbodyColourDirection
    SpectralEmissionTest.DopplerShiftDirection
    SpectralEmissionTest.SpinDisplayFormat
    PROPERTIES LABELS "Mandatory;Correctness"
)

message(STATUS "CTest labels configured for Sirius test suite")
