# =============================================================================
# CTestTestfile.cmake - Test Labels for Mandatory Gating
# =============================================================================
# Generated by Sirius build system
# Governance: docs/specification.md, Test Coverage Requirements
#
# Labels:
#   Mandatory   - Build fails if these tests fail
#   Correctness - Mathematical invariant tests
#   Stability   - Numerical stability tests
#   Performance - FPS/resource metrics (warning only)
# =============================================================================

# Apply labels by test name patterns
set_tests_properties(
    DualNumberTests.AdditiveIdentity
    DualNumberTests.MultiplicativeIdentity
    DualNumberTests.AdditiveInverse
    DualNumberTests.AdditionCommutativity
    DualNumberTests.MultiplicationCommutativity
    DualNumberTests.AdditionAssociativity
    DualNumberTests.Distributivity
    DualNumberTests.Nilpotency
    DualNumberTests.ProductFormula
    DualNumberTests.DivisionFormula
    DualNumberTests.SinDerivative
    DualNumberTests.SinDerivativeMultipleAngles
    DualNumberTests.CosDerivative
    DualNumberTests.SqrtDerivative
    DualNumberTests.SqrtDerivativeMultiplePoints
    DualNumberTests.ChainRuleSinSquare
    PROPERTIES LABELS "Mandatory;Correctness"
)

set_tests_properties(
    TensorTests.VectorZeroInitialization
    TensorTests.VectorElementAccess
    TensorTests.VectorAddition
    TensorTests.VectorScalarMultiplication
    TensorTests.VectorLength
    TensorTests.VectorUnaryMinus
    TensorTests.MatrixZeroInitialization
    TensorTests.MinkowskiSymmetry
    TensorTests.MinkowskiDiagonal
    TensorTests.MinkowskiSignature
    TensorTests.InnerProductSpatial
    TensorTests.NullVectorInnerProduct
    TensorTests.Tensor3ZeroInitialization
    TensorTests.FlatSpaceChristoffelZero
    TensorTests.ChristoffelSymmetry
    PROPERTIES LABELS "Mandatory;Correctness"
)

set_tests_properties(
    SchwarzschildTests.MetricIsDiagonal
    SchwarzschildTests.MetricIsSymmetric
    SchwarzschildTests.MetricHasLorentzianSignature
    SchwarzschildTests.AsymptoticFlatness
    SchwarzschildTests.EventHorizonGtt
    PROPERTIES LABELS "Mandatory;Correctness"
)

set_tests_properties(
    ChristoffelTests.ChristoffelSymmetry
    ChristoffelTests.MinkowskiChristoffelsZero
    ChristoffelTests.SchwarzschildChristoffelNonZero
    PROPERTIES LABELS "Mandatory;Correctness"
)

set_tests_properties(
    GeodesicEquationTests.FlatSpaceAccelerationZero
    GeodesicEquationTests.NullVelocityPreserved
    PROPERTIES LABELS "Mandatory;Correctness"
)

set_tests_properties(
    KerrMetricTests.MetricIsSymmetric
    KerrMetricTests.ReducesToMinkowskiFarField
    KerrMetricTests.ReducesToSchwarzchildZeroSpin
    KerrMetricTests.FrameDraggingTermExists
    KerrMetricTests.MetricHasLorentzianSignature
    PROPERTIES LABELS "Mandatory;Correctness"
)

set_tests_properties(
    ReissnerNordstromTests.MetricIsDiagonal
    ReissnerNordstromTests.MetricIsSymmetric
    ReissnerNordstromTests.MetricHasLorentzianSignature
    ReissnerNordstromTests.ReducesToSchwarzschildZeroCharge
    ReissnerNordstromTests.AsymptoticFlatness
    ReissnerNordstromTests.OuterHorizonFormula
    ReissnerNordstromTests.DeterminantIsNegative
    PROPERTIES LABELS "Mandatory;Correctness"
)

set_tests_properties(
    NumericalMetricTests.MinkowskiADMReturnsMinkowski
    NumericalMetricTests.MetricIsSymmetric
    NumericalMetricTests.MetricHasNegativeGtt
    NumericalMetricTests.InverseMetricIdentity
    NumericalMetricTests.SchwarzschildAsymptoticFlatness
    NumericalMetricTests.NoNaNInMetric
    PROPERTIES LABELS "Mandatory;Correctness"
)

# Stability tests - mandatory for production
set_tests_properties(
    NumericalStabilityTests.DualZeroHandling
    NumericalStabilityTests.DualDivisionBySmall
    NumericalStabilityTests.DualSqrtNearZero
    NumericalStabilityTests.SchwarzschildNearHorizon
    PROPERTIES LABELS "Mandatory;Stability"
)

# Benchmark tests - performance validation (soft gate)
set_tests_properties(
    GeodesicBenchmarks.CircularOrbitPeriod
    GeodesicBenchmarks.ISCORadius
    GeodesicBenchmarks.PhotonSphereRadius
    GeodesicBenchmarks.WeakFieldLightDeflection
    GeodesicBenchmarks.SolarDeflectionOrder
    GeodesicBenchmarks.GeodesicConservedQuantities
    GeodesicBenchmarks.RadialFallProperTime
    GeodesicBenchmarks.PerihelionPrecession
    GeodesicBenchmarks.VerificationDataPoints
    PROPERTIES LABELS "Correctness"
)

# FPS benchmark tests - performance validation (soft gate)
set_tests_properties(
    FPSBenchmarks.MinkowskiFPS
    FPSBenchmarks.SchwarzschildFPS
    FPSBenchmarks.SchwarzschildNearHorizonFPS
    FPSBenchmarks.KerrFPS
    FPSBenchmarks.KerrSpinComparison
    FPSBenchmarks.MetricComparison
    FPSBenchmarks.StepCountScaling
    PROPERTIES LABELS "Performance"
)

# Metric loader chain integration tests
set_tests_properties(
    MetricLoaderChainTests.AllMetricsHaveName
    MetricLoaderChainTests.AllMetricsEvaluateAtStandardPosition
    MetricLoaderChainTests.AllMetricsHaveLorentzianSignature
    MetricLoaderChainTests.AllMetricsAreSymmetric
    MetricLoaderChainTests.KerrReducesToSchwarzschild
    MetricLoaderChainTests.RNReducesToSchwarzschild
    MetricLoaderChainTests.FarFieldAsymptoticFlatness
    MetricLoaderChainTests.MinkowskiIsExactlyFlat
    MetricLoaderChainTests.SequentialEvaluationsStable
    PROPERTIES LABELS "Mandatory;Correctness"
)

# FPS threshold tests (TSPF001A)
set_tests_properties(
    FPSThresholdTests.FrameBudgetCalculations
    FPSThresholdTests.ResolutionCalculations
    FPSThresholdTests.TargetsExceedBounds
    FPSThresholdTests.MinkowskiEvaluationTime
    FPSThresholdTests.MetricComplexityOrdering
    FPSThresholdTests.EvaluationConsistency
    FPSThresholdTests.NoNaNInCriticalPath
    PROPERTIES LABELS "Performance"
)

# Memory usage tests (TSPF002A)
set_tests_properties(
    MemoryUsageTests.FundamentalTypeSizes
    MemoryUsageTests.DualNumberSize
    MemoryUsageTests.Vec4Size
    MemoryUsageTests.Metric4DSize
    MemoryUsageTests.PerRayMemory
    MemoryUsageTests.NumericalMetricSmallGrid
    MemoryUsageTests.TotalVRAMAnalytic1080p
    MemoryUsageTests.TotalVRAMNumerical1080p
    MemoryUsageTests.VectorAllocationSafe
    MemoryUsageTests.MetricEvaluationNoLeak
    PROPERTIES LABELS "Performance"
)

# =============================================================================
# RESOLVED: Tests now passing with RK45 integrator (Dec 2024)
# =============================================================================
# These tests previously failed with the Störmer-Verlet integrator but now
# pass after upgrading to adaptive RK45 (Dormand-Prince) integration.
# Conservation law tests verify bounded drift over 1000 integration steps.
# =============================================================================
set_tests_properties(
    ConservationLawTests.NullConditionPreservedSchwarzschild
    ConservationLawTests.NullConditionPreservedKerr
    ConservationLawTests.KillingEnergyConservedKerr
    ConservationLawTests.AllConservedQuantitiesSchwarzschild
    ConservationLawTests.KillingEnergyConservedSchwarzschild
    ConservationLawTests.KillingAngularMomentumConservedSchwarzschild
    ConservationLawTests.KillingAngularMomentumConservedKerr
    PROPERTIES LABELS "Mandatory;Stability"
)

# Geodesic path tests that now pass with RK45
# Note: PhotonSphereRadius and RadialInfallApproachesHorizon are DISABLED
# as they test inherently unstable behaviors
set_tests_properties(
    GeodesicPathTests.PhotonSphereInstability
    GeodesicPathTests.WeakFieldLightDeflection
    GeodesicPathTests.KerrFrameDragging
    GeodesicPathTests.PhiWrapContinuity
    GeodesicPathTests.MetricSignatureCorrect
    GeodesicPathTests.KerrMetricSignature
    PROPERTIES LABELS "Correctness"
)

# Determinism tests - mandatory for production reproducibility
set_tests_properties(
    DeterminismTests.DualArithmeticDeterminism
    DeterminismTests.SchwarzschildMetricDeterminism
    DeterminismTests.KerrMetricDeterminism
    DeterminismTests.ChristoffelDeterminism
    DeterminismTests.GeodesicIntegrationDeterminism
    DeterminismTests.InnerProductDeterminism
    DeterminismTests.NullNormalizationDeterminism
    PROPERTIES LABELS "Mandatory;Stability"
)

# Metric derivative validation tests (TSPH012A)
set_tests_properties(
    MetricDerivativeTests.KerrSchildDerivativeSymmetry
    MetricDerivativeTests.KerrSchildFiniteDifferenceAgreement
    MetricDerivativeTests.KerrSchildNonZeroDerivatives
    MetricDerivativeTests.EllisDrainholeDerivativeSymmetry
    MetricDerivativeTests.EllisDrainholeRadialDerivative
    MetricDerivativeTests.EllisDrainholeAngularDerivative
    MetricDerivativeTests.EllisDrainholeFiniteDifferenceAgreement
    MetricDerivativeTests.AlcubierreDerivativeSymmetry
    MetricDerivativeTests.AlcubierreTimeDerivative
    MetricDerivativeTests.AlcubirrreFiniteDifferenceAgreement
    MetricDerivativeTests.AlcubierreOutsideBubble
    MetricDerivativeTests.ChristoffelSymmetryFromDerivatives
    PROPERTIES LABELS "Mandatory;Correctness"
)

# DNGR validation tests - FIDO frame consistency (TSCM005A)
set_tests_properties(
    FIDOFrameTests.RhoComputationCorrect
    FIDOFrameTests.DeltaComputationCorrect
    FIDOFrameTests.FrameDraggingZeroForSchwarzschild
    FIDOFrameTests.FrameDraggingIncreasesWithSpin
    FIDOFrameTests.LapseFunctionLessThanOne
    FIDOFrameTests.LapseFunctionApproachesOneAtInfinity
    FIDOFrameTests.FIDOBasisOrthonormalAtEquator
    FIDOFrameTests.CircularGeodesicSpeedSubluminal
    FIDOFrameTests.CircularGeodesicSpeedIncreasesNearHorizon
    FIDOFrameTests.SchwarzschildCircularSpeed
    FIDOFrameTests.KerrReducesToSchwarzschildAtZeroSpin
    PROPERTIES LABELS "Correctness"
)

# DNGR validation tests - G-factor (TSCM006A)
set_tests_properties(
    GFactorTests.StaticCameraGravitationalRedshift
    GFactorTests.SRFactorOneWhenStationary
    GFactorTests.ApproachingRayBlueshift
    GFactorTests.RecedingRayRedshift
    GFactorTests.TransverseRayDoppler
    GFactorTests.FrameDraggingEffect
    GFactorTests.NoFrameDraggingInSchwarzschild
    GFactorTests.SchwarzschildISCOGravitationalRedshift
    GFactorTests.AsymptoticGFactorApproachesOne
    GFactorTests.GFactorAlwaysPositive
    GFactorTests.GFactorIsFinite
    GFactorTests.HighSpeedApproachingBlueshift
    GFactorTests.HighSpeedRecedingRedshift
    PROPERTIES LABELS "Correctness"
)

# DNGR validation tests - Geodesic deviation (TSCM007A)
set_tests_properties(
    GeodesicDeviationTests.MinkowskiRiemannZero
    GeodesicDeviationTests.DeviationConstantInFlatSpace
    GeodesicDeviationTests.SchwarzschildRiemannNonzero
    GeodesicDeviationTests.RiemannDecreasesWithDistance
    GeodesicDeviationTests.EllipseSemiAxesPositive
    GeodesicDeviationTests.CircularBundleInitialization
    GeodesicDeviationTests.BundleInitializationCorrect
    GeodesicDeviationTests.PropagationRemainsFinite
    PROPERTIES LABELS "Correctness"
)

# =============================================================================
# MANDATORY: Killing Vector Conservation Tests (TSDG006A)
# =============================================================================
# These tests verify that Killing vector conserved quantities (energy, angular
# momentum) remain bounded during geodesic integration. Required for all
# stationary and axisymmetric spacetimes.
set_tests_properties(
    MandatoryKillingTests.SchwarzschildEnergyConservation
    MandatoryKillingTests.SchwarzschildAngularMomentumConservation
    MandatoryKillingTests.KerrEnergyConservation
    MandatoryKillingTests.KerrAngularMomentumConservation
    MandatoryKillingTests.ReissnerNordstromEnergyConservation
    PROPERTIES LABELS "Mandatory;Stability"
)

# =============================================================================
# GPU Conservation Validation Tests (TSDG005A)
# =============================================================================
set_tests_properties(
    GPUConservationTests.DebugBufferAnalysis
    GPUConservationTests.SpecificationCompliance
    PROPERTIES LABELS "Mandatory;Stability"
)

# =============================================================================
# GPU/CPU Parity Tests (TSIN006A)
# =============================================================================
set_tests_properties(
    CPUGPUParityTests.BaselineCPUIntegration
    CPUGPUParityTests.ReferenceRayGridGeneration
    PROPERTIES LABELS "Mandatory;Correctness"
)

# =============================================================================
# Spectral Validation Tests (TSSP002A)
# =============================================================================
set_tests_properties(
    SpectralValidationTests.PlanckFunctionBasic
    SpectralValidationTests.PlanckFunctionMonotonicity
    SpectralValidationTests.WienDisplacementLaw
    SpectralValidationTests.SolarPeakWavelength
    SpectralValidationTests.CandelaColor
    SpectralValidationTests.WienKnownValues
    SpectralValidationTests.RedshiftIntensityScaling
    SpectralValidationTests.RedshiftWavelengthTransform
    SpectralValidationTests.ColorTemperatureOrdering
    SpectralValidationTests.LimbDarkeningCoefficient
    SpectralValidationTests.BlackbodyColorProgression
    SpectralValidationTests.StefanBoltzmannLaw
    SpectralValidationTests.SolarLuminosity
    PROPERTIES LABELS "Correctness"
)

# =============================================================================
# Analytic Validation Tests (TSDG008A)
# =============================================================================
set_tests_properties(
    AnalyticValidationTests.SchwarzschildHorizonRadius
    AnalyticValidationTests.SchwarzschildPhotonSphere
    AnalyticValidationTests.SchwarzschildISCO
    AnalyticValidationTests.SchwarzschildOrbitalVelocity
    AnalyticValidationTests.KerrHorizonRadius
    AnalyticValidationTests.KerrISCOPrograde
    AnalyticValidationTests.KerrISCODecreaseWithSpin
    AnalyticValidationTests.KerrErgosphereAtEquator
    AnalyticValidationTests.KerrErgosphereAtPole
    AnalyticValidationTests.WeakFieldDeflectionFormula
    AnalyticValidationTests.SolarDeflectionOrderOfMagnitude
    AnalyticValidationTests.KerrReducesToSchwarzschildAtZeroSpin
    AnalyticValidationTests.AsymptoticFlatness
    AnalyticValidationTests.SchwarzschildKretschmannScalar
    AnalyticValidationTests.KretschmannMonotonicDecrease
    AnalyticValidationTests.HorizonMetricDegeneracy
    AnalyticValidationTests.SchwarzschildISCOEnergy
    PROPERTIES LABELS "Mandatory;Correctness"
)

message(STATUS "CTest labels configured for Sirius test suite")


